### ISSUE TITLE
Add configuration for skipping cbindgen step and allow specifying a pre-generated header

### ISSUE THREAD

**Issue by sdroege** [lu-zero/cargo-c#101]
See summary. In my case I'd prefer shipping the header of the original C library (with documentation, various custom #defines, etc).

**Comment by sdroege** [comment]
Also needs configuration to install the header directly into the include directory instead of into a subdirectory with the crate name.

How would you like to name these configurations?

```toml
[package.metadata.capi]
header_name = "ebur128.h"
# if not given it will be generated, otherwise it will be installed from there relative to the manifest directory
pregenerated_header = "include/ebur128.h"
# defaults to true, if true then header goes into includedir/package, otherwise directly includedir
header_subdirectory = false
```
