### ISSUE TITLE
Add a mean to customize the pkg-config generation

### ISSUE THREAD

**Issue by lu-zero** [lu-zero/cargo-c#12]
- [ ] Draft `Cargo.toml` metadata entries
- [ ] Implement the support for it
- [ ] Write a testcase

**Comment by sdroege** [comment]
What I would need here is:
- setting a different name
- setting a different version

For that something like the following would work for me

```toml
[package.metadata.capi]
pkg_config_name = "libebur128"
pkg_config_version = "1.2.4"
```
Or alternatively in a `[package.metadata.capi.pkg_config]` sub-group.

I could implement those but I don't know what your bigger plans with customization here are.
