### ISSUE TITLE
Modules/plugin supports

### ISSUE THREAD

**Issue by gdesmott** [lu-zero/cargo-c#135]
`gst-plugins-rs`, the GStreamer Rust plugins, are currently [not statically linkable](https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/issues/133) with a C application. One of the issue is the lack of pkg-config file to retrieve its linking flags. [It's been suggested](https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/issues/133#note_700866) that `cargo-c` could be a good fit for this as it already has support for pkg-config generation.

Would you be willing to extend `cargo-c` to support such use case?

cc @sdroege @xclaesse

**Comment by sdroege** [comment]
Basically this would mean
 - `build` wouldn't include a soname and stuff
 - `pkg-config` file would be generated
 - no header is generated or installed
 - installation of the generated .so (and pkg-config) should be in a special location, not the standard library path

@lu-zero What do you think?

**Comment by lu-zero** [comment]
Ideally we just need to add a key to ignore the architecture-provided link lines.

Right now I'm updating to the latest cargo, hopefully this one won't make release libraries with llvm-ir in strange .o.

**Comment by lu-zero** [comment]
@gdesmott if you want to give it a try and send a patch I'm quite open to add this feature :)

**Comment by gdesmott** [comment]
Cool! So how would prefer to have this API-wise?

Should we add something like this to disable the so name mangling and header generation?

```toml
[package.metadata.capi]
library = false
```

Or do you prefer to have individual settings?

```toml
[package.metadata.capi.header]
enabled = false

[package.metadata.capi.library]
so_name_versioning = false
```

Regarding the custom install path should we have something like this?

```toml
[package.metadata.capi.library]
install_subdir = "gstreamer-1.0"
```
which would install to `$dest/$libdir/$subdir`.

**Comment by lu-zero** [comment]
> Or do you prefer to have individual settings?
> 
> ```toml
> [package.metadata.capi.header]
> enabled = false
> 
> [package.metadata.capi.library]
> so_name_versioning = false
> ```

I do

> Regarding the custom install path should we have something like this?
> 
> ```toml
> [package.metadata.capi.library]
> install_subdir = "gstreamer-1.0"
> ```
> 
> which would install to `$dest/$libdir/$subdir`.

Sounds good to me. :)

**Comment by sdroege** [comment]
Seems like a good approach to me too

**Comment by gdesmott** [comment]
```toml
[package.metadata.capi.header]
enabled = false
```

Another option if you don't mind breaking the API would be to replace `generation` from a boolean to an enum: `cbindgen`, `copy`, `disabled`.
