### ISSUE TITLE
pkg-config: allow to define Requires and Requires.private

### ISSUE THREAD

**Issue by gdesmott** [lu-zero/cargo-c#139]
The pkg-config generator [has code to generate Requires](https://github.com/lu-zero/cargo-c/blob/master/src/pkg_config_gen.rs#L165) but there is currently no way to use it.

Should we add something like so users can define them manually?

```toml
[package.metadata.capi.pkg_config]
requires = "gstreamer-1.0, gstreamer-base-1.0"
requires_private = "gobject-2.0, glib-2.0 >= 2.56.0, gmodule-2.0"
```
