### ISSUE TITLE
Using `subdirectory = false` leads to empty header file

### ISSUE THREAD

**Issue by mgeier** [lu-zero/cargo-c#216]
To reproduce, use `subdirectory = false` in [the example project's `Cargo.toml`](../blob/master/example-project/Cargo.toml).

```toml
[package.metadata.capi.header]
subdirectory = false
```

After `cargo cinstall`, the generated file `/usr/local/include/example_project.h` is empty, it has a size of 0 bytes.

Same for `subdirectory = ""`.
