### ISSUE TITLE
Add a min_version metadata

### ISSUE THREAD

**Issue by lu-zero** [lu-zero/cargo-c#99]
So future cargo-c version could tell if they are incompatible and require the user to upgrade when needed.

``` toml
[package.metadata.capi]
min_version = "0.6.11"
```
